apiVersion: v1
kind: Service
metadata:
  name: {{ include "durantic.fullname" . }}
  labels:
    {{- include "durantic.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if ne (.Values.service.httpPort | toString) "0" }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.controlPlane.enableGrpcServer }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "durantic.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.grpcService.enabled .Values.controlPlane.enableGrpcServer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "durantic.fullname" . }}-grpc
  labels:
    {{- include "durantic.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
  {{- with .Values.grpcService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpcService.type }}
  ports:
    - port: {{ .Values.grpcService.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- if .Values.grpcService.targetReleaseName }}
    app.kubernetes.io/name: {{ include "durantic.name" . }}
    app.kubernetes.io/instance: {{ .Values.grpcService.targetReleaseName }}
    {{- else }}
    {{- include "durantic.selectorLabels" . | nindent 4 }}
    {{- end }}
{{- end }}